### ISSUE TITLE
Make FileSharingApi#create save share URL if possible

### ISSUE THREAD

**Issue by Quintasan** [dachinat/nextcloud#16]
Creating a public share with URL using https://github.com/dachinat/nextcloud/blob/master/lib/nextcloud/ocs/file_sharing_api.rb#L76 doesn't get you the share URL back. With the current behavior if I create 100 shares then I'll have to make additional 100 API calls to get all the URLs.

If I recall correctly, when you create a public share the URL should be available under `ocs.data.url`.

**Comment by Quintasan** [comment]
Welp, I did it myself - see #18

**Comment by dachinat** [comment]
Thanks a lot, PR accepted
